# SPDX-FileCopyrightText: 2017-present Tobias Kunze
# SPDX-License-Identifier: AGPL-3.0-only WITH LicenseRef-Imanage-AGPL-3.0-Terms

# Generated by Django 1.11.4 on 2017-09-06 05:53

from django.db import migrations, models

import imanage.event.models.event


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0004_event_update_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="custom_css",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=imanage.event.models.event.event_css_path,
            ),
        ),
    ]
