# Generated by Django 6.0.1 on 2026-01-26 19:55

import imanage.common.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0091_question_identifier_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="internal_text",
            field=imanage.common.models.fields.MarkdownField(null=True),
        ),
    ]
