# Generated by Django 6.0.1 on 2026-01-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0092_add_review_internal_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='file_hash',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='file_size',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='mime_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
