# Generated by Django 6.0.1 on 2026-01-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0093_resource_file_hash_resource_file_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="allowed_file_types",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="max_file_size",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
